[workspace]
name = "benchmarking"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = ">=3.11"
numpy = "*"
pandas = "*"
matplotlib = "*"
mplfinance = "*"
pillow = "*"

[tasks]
main = { cmd = ["python", "-m", "scripts.main"] }
image = { cmd = ["python", "-m", "image_editing.image"] }
report = { cmd = ["python", "-m", "scripts.main", "--report", "--all"] }
compare = { cmd = ["python", "-m", "image_editing.compare_runs"] }